# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - e3d_bot_controller

  e3d_bot_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - turnTable_to_base
      - l1_to_base
      - l2_to_l1
      - endeffector_to_l2
    action_ns: follow_joint_trajectory
    default: true